---
title: "PCA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create a pop info factor

```{r}
pop_info <- read.table("Boar_info.txt", sep="\t", h=T, stringsAsFactors = F)
names(pop_info)
pop_info$PCA.cluster <- as.factor(pop_info$PCA.cluster)
pop_info_pca <- pop_info$PCA.cluster
```

```{r}
pop_info_pca #
all_info_pca <- c("1","1","1","1","1","1","1","1","1","1","1","1","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","3","2","1","2","1","2","2","2","1","hyb1","1","1","2","4","2","2","1","hyb3","1","1","1","2","1","1","1","2","2","2","2","2","2","2","2","2","2","hyb5","hyb2", "hyb6","2","hyb4","2","4","4","4","hyb8","4","4","4","hyb7", "hyb9","4","4","4","4","5","5","5","5","5","5","5","5","5")

all_info_pca <- as.factor(all_info_pca)
all_info_pca
```

## PCA using SNPRelate

```{r}
library("SNPRelate")
boar_gds <- snpgdsPED2GDS("Board.filtered.0.05.ped", "Board.filtered.0.05.map", "Board.filtered.0.05.gdsfn")
genofile <- snpgdsOpen("Board.filtered.0.05.gdsfn")



snpset.id <- unlist(genofile)
View(snpset.id)



pop_code <- read.gdsn(index.gdsn(genofile, path="sample.annot/family"))
pop_code <- scan("pop.txt", what=character())
table(pop_code)
head(pop_code)
```


## PCA with adegenet

```{r}
library(adegenet)

obj <- df2genind(board_filtered_0.05_genotypes, ploidy=2, ncode=1)

pca = dudi.pca(obj, center=TRUE, scale=FALSE)
s.label(pca$li)
s.class(pca$li, fac=pop_info_pca, col=funky(13))

s.class(pca$li, fac=pop_info_pca,
        xax=1,yax=2,
        col=transp(funky(13),.6),
        axesel=FALSE, cstar=0, cpoint=3, grid = F)
add.scatter.eig(pca$eig[1:50],3,1,2, ratio=.3)
```

## PCA including some pigs genotypes

```{r}
obj2 <- df2genind(all_genotypes, ploidy=2, ncode=1)
pca2 = dudi.pca(obj2, center=TRUE, scale=FALSE)
s.label(pca2$li)
s.class(pca2$li, fac=all_info_pca, col=funky(13))
s.class(pca2$li, fac=all_info_pca,
        xax=1,yax=2,
        col=transp(funky(13),.6),
        axesel=FALSE, cstar=0, cpoint=3, grid = F)
add.scatter.eig(pca$eig[1:50],3,1,2, ratio=.3)
```